default_config:

homeassistant:
  internal_url: !env_var HA_INTERNAL_URL
  external_url: !env_var HA_EXTERNAL_URL

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 172.16.0.0/12
    - 10.0.0.0/8
    - 192.168.0.0/16

mqtt:
  discovery: true
  cover:
    - name: "Cửa cuốn kho"
      unique_id: shed_garage_door
      device_class: garage
      state_topic: "shed/state/door"
      command_topic: "shed/cmd/door"
      payload_open: "OPEN"
      payload_close: "CLOSE"
      payload_stop: "STOP"
      state_open: "open"
      state_closed: "closed"
      optimistic: false

camera:
  - platform: generic
    name: "Shed AI Overlay"
    still_image_url: "http://127.0.0.1:8080/video_feed"
    stream_source: "http://127.0.0.1:8080/video_feed"
    verify_ssl: false

lovelace:
  mode: yaml
